spring:
  application:
    name: greeting-qards-service
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/qards
    driver-class-name: org.postgresql.Driver
    username: jasondevlin
    password:
  jpa:
    show-sql: true # Show SQL queries in console
    hibernate:
      ddl-auto: update # Updates schema automatically

jwt:
  secret: ${CLIENT_SECRET}

wallet:
  api:
    host: https://api.circle.com
    base-path: /v1/w3s
    key: ${WALLET_API_KEY}
    app-id: ${WALLET_APP_ID}
    public-key: ${WALLET_PUBLIC_KEY}
    secret: ${CLIENT_SECRET}