spring:
  application:
    name: greeting-qards-service
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/qards
    driver-class-name: org.postgresql.Driver
    username: jasondevlin
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true # Show SQL queries in console
    hibernate:
      ddl-auto: update # Updates schema automatically

wallet:
  api:
#    url: http://localhost:8080/api/v1/wallets
    key: ${WALLET_API_KEY}
    app-id: ${WALLET_APP_ID}